server:
  port: 8181

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://dev:dev@localhost:27019/user_db?authSource=admin

logging:
  level:
    org.springframework.security: INFO

app:
  security:
    jwt:
      issuer: restaurant-os
      private-key: classpath:keys/app_private.pem
      public-key: classpath:keys/app_public.pem
      cookie:
        secure: false
        same-site: Lax
