server:
  port: 8182

spring:
  application:
      name: user-service
  data:
    mongodb:
      uri: mongodb://dev:dev@localhost:27019/user_db?authSource=admin
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.restaurantos.userservice: DEBUG
    org.springframework.security: DEBUG
    com.restaurantos.coresecurity: DEBUG

