server:
  port: 8184

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3308/order_db
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.restaurantos.orderservice: DEBUG
    org.springframework.security: DEBUG
    com.restaurantos.coresecurity: DEBUG
