logging:
  level:
    org.springframework.security: DEBUG

#app:
#  security:
#    internal:
#      jwt:
#        secret: "4bdcd972736c429153d3fdf60081bffd"
#        access-token-ttl: PT15M
#        refresh-token-ttl: P1D
#    customer:
#      jwt:
#        secret: "e9t3pWc4m2x8v0h5s2Y7Z3gftk7571b9g6T2D4F8M1P7R0L3C5A9U2E7I4O6Y1T3"
#        access-token-ttl: PT30M
#        refresh-token-ttl: P7D
#    otp:
#      jwt:
#        secret: "o9t3pWc4m2x8v0h5hs78mf30h4N8B1K9g6T2D4F8M1P7R0L3C5A9U2E7I4O6Y1T3"
#        access-token-ttl: PT60M
