server:
  port: 8183

spring:
  application:
    name: menu-service
  data:
    mongodb:
      uri: mongodb://dev:dev@localhost:27018/menu_db?authSource=admin
      auto-index-creation: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.restaurantos.menuservice: DEBUG
    org.springframework.security: DEBUG
    com.restaurantos.coresecurity: DEBUG
